languageCode = "en-us"

theme = "scarecrow"
baseURL = "http://www.strootje.com/"
title = "strootje"
DefaultContentLanguage = "en"
paginate = 6

[languages.en]
languageName = "English"
weight = 1
# [languages.nl]
# languageName = "Nederlands"
# weight = 2

[params]
	author = "Bas Stroosnijder"
	logo = "/images/logo.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[params.about]
		title = "Bas Stroosnijder"
		tagline = "FOSS since 1991"
		[params.about.logo]
			src = "/images/about.jpg"
	[[params.poweredBy]]
		title = "Hugo"
		url = "https://gohugo.io"
	[[params.poweredBy]]
		title = "Scarecrow"
		url = "https://strootje.com/projs/scarecrow"
	# [[params.poweredBy]]
	# 	title = "Bulma"
	# 	url = "https://bulma.io"
	# 	badge = "https://bulma.io/images/made-with-bulma--black.png"
	# [params.widgets]
	# 	sidebar = [ "powered-by" ]

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
# [[menu.main]]
# 	name = "Booklist"
# 	url = "/books/"
# 	weight = 3

[[menu.social]]
	name = "github"
	url = "https://github.com/strootje/"
	weight = 1
[[menu.social]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/bas-stroosnijder/"
	weight = 3
