languageCode = "en-us"

theme = "scarecrow"
baseURL = "https://www.strootje.com/"
title = "strootje"
DefaultContentLanguage = "en"
paginate = 6

[languages.en]
languageName = "English"
weight = 1
[languages.nl]
languageName = "Nederlands"
weight = 2

[params]
	author = "Bas Stroosnijder"
	logo = "/images/logo.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[params.about]
		title = "Bas Stroosnijder"
		tagline = "FOSS since 1991"
		[params.about.logo]
			src = "/images/about.jpg"
	[params.menu.social]
		target = "blank"
	[params.widgets]
		sidebar = [ "powered-by" ]
	[[params.poweredBy]]
		title = "Hugo"
		version = "0.54.0/extended"
		url = "https://gohugo.io"
	[[params.poweredBy]]
		title = "Scarecrow"
		version = "0.1.0"
		url = "https://strootje.com/projs/scarecrow"
	[[params.poweredBy]]
		title = "Bulma"
		version = "0.7.4"
		url = "https://bulma.io"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 3

[[menu.social]]
	name = "github"
	url = "https://github.com/strootje/"
	pre = "fab fa-fw fa-lg fa-github"
	weight = 1
[[menu.social]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/bas-stroosnijder/"
	pre = "fab fa-fw fa-lg fa-linkedin"
	weight = 3
