languageCode = "en-us"

theme = "scarecrow"
title = "strootje"
baseURL = "https://strootje.com/"
DefaultContentLanguage = "en"
paginate = 6

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"

[languages.en]
	languageName = "English"
	contentDir = "content/en"
	weight = 1

[params]
	callToAction = "/contact"
[params.options]
	showCallToAction = false
	showFollow = true
	showRelated = true
	showShare = true
[params.author]
	name = "Bas Stroosnijder"
	tagline = "FOSS since 1991"
	logo = "images/about.jpg"
[params.social]
	github = "strootje"
	linkedin = "bas-stroosnijder"
	rss = "posts"

[[menu.main]]
	name = "About"
	weight = 100
	title = "about"
	url = "/about"
[[menu.main]]
	name = "Contact"
	weight = 200
	title = "contact"
	url = "/contact/"
